trigger:
- master

pool:
  vmImage: 'ubuntu-latest'  # Or use your self-hosted agent if Docker runs there

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    docker build -t legacy-app:latest .
  displayName: 'Build Docker Image'

- script: |
    docker rm -f legacy-container || true
    docker run -d -p 9090:3000 --name legacy-container legacy-app:latest
  displayName: 'Run Docker Container'
