trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Checkout@1
  inputs:
    repository: self
    fetchDepth: 1

- script: |
    echo "Checking if task exists"
    if [[ "$(containsValue(steps, '6d15af64-176c-496d-b583-fd2ae21d4df4'))" == "True" ]]; then
        echo "Task found!"
    else
        echo "Task not found!"
    fi
  displayName: 'Task Existence Check'

- script: |
    if [ "$(system.debugContext)" == "true" ]; then
        echo "Debugging enabled"
    else
        echo "Debugging not enabled"
    fi
  displayName: 'Debug Context Check'

- task: 6d15af64-176c-496d-b583-fd2ae21d4df4@1
  inputs:
    repository: self
    fetchDepth: 1
