# Azure DevOps Pipeline with Self-Hosted Agent and k6 Performance Testing

trigger:
- master  # Trigger pipeline on commits to master branch

# Use your self-hosted agent
pool:
  name: Default
  demands:
    - Agent.Name -equals MANASA

steps:
- script: echo "Starting the CI/CD pipeline..."
  displayName: 'Initialize Pipeline'

- script: |
    echo "Building the project..."
    echo "Run necessary build commands here"
  displayName: 'Build Step'

- script: |
    echo "Running unit tests..."
    echo "Execute test scripts here"
  displayName: 'Run Unit Tests'

- script: |
    echo "Starting Performance Test..."
    C:\ProgramData\chocolatey\bin\k6.exe run E:\TP\legacy-app\loadTest.js
  displayName: 'Run k6 Performance Test'

- script: |
    echo "Deploying the application..."
    echo "Add deployment commands here"
  displayName: 'Deployment Step'
