trigger:
  - master  # Use your self-hosted agent by specifying its name in the pool

pool:
  name: Default         # or your custom pool name
  demands:
    - Agent.Name -equals MANASA

steps:
  - script: echo Hello from MANASA agent!
    displayName: 'Run a one-line script'

  - script: |
      echo Running on self-hosted agent: MANASA
      echo Add steps to build, test, or deploy here.
    displayName: 'Run a multi-line script'

  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'Install dependencies'

  - script: |
      docker build -t legacy-app:latest .
    displayName: 'Build Docker Image'

  - script: |
      docker rm -f legacy-container || true
      docker run -d -p 9090:3000 --name legacy-container legacy-app:latest
    displayName: 'Run Docker Container'
