trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: Checkout@1
  inputs:
    repository: self
    fetchDepth: 1

- task: MSBuild@1
  inputs:
    solution: '**/*.sln'
    msbuildArgs: '/p:Configuration=Release'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
    publishLocation: 'Container'
