trigger:
- master

pool:
  name: Default
  demands:
    - Agent.Name -equals MANASA

steps:
- script: echo "Starting the CI/CD pipeline..."
  displayName: 'Initialize Pipeline'

- script: |
    echo "Building the project..."
    echo "Run necessary build commands here"
  displayName: 'Build Step'

- script: |
    echo "Running unit tests..."
    echo "Execute test scripts here"
  displayName: 'Run Unit Tests'


- script: |
    k6 run loadTest.js
  displayName: 'Run Performance Test'  # Running the K6 test script
